title: '深圳 Linux 用户组 / Shenzhen GNU/Linux User Group'
description: "深圳 GNU/Linux 用户组，深圳开源社区，深圳开源用户，Linux"

header_pages:

  - index.md
  - blog.md
  - join.md
  - donate.md
  - about.md

footer: 'follow us on <a href="https://github.com/shenzhenlug">GitHub</a>'

plugins:
  - jekyll-seo-tag
  
# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
